version: "3.9"

services:

  database:
    image: mysql:5.7.16
    container_name: database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: students
      MYSQL_USER: students
      MYSQL_PASSWORD: students
    volumes:
      - "./database/mysql.cnf:/etc/mysql/conf.d/mysql.cnf"
      - "./database/setup.sql:/docker-entrypoint-initdb.d/setup.sql"
    command: [ "--default-authentication-plugin=mysql_native_password" ]

  zookeeper:
    image: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  
  kafka:
    image: confluentinc/cp-kafka
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_HOST://kafka:29092
      LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
  
  debezium-connect:
    image: debezium/connect
    container_name: debezium-connect
    hostname: debezium-connect
    ports:
      - '8083:8083'
    environment:
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: debezium_connect_config
      OFFSET_STORAGE_TOPIC: debezium_connect_offsets
      STATUS_STORAGE_TOPIC: debezium_connect_status
      BOOTSTRAP_SERVERS: kafka:29092
    depends_on:
      - kafka
      - database
      
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "9081:9081"
    environment:
      - SERVER_PORT=9081
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
      - KAFKA_CLUSTERS_0_NAME=local
    depends_on:
      - kafka